#!/usr/bin/env python3
"""Stamp wormlens/_version.py from git describe.

Run by:
  - git hooks (post-merge, post-checkout) installed in .git/hooks/
  - the release pipeline, before `python -m build`
  - by hand if you want a fresh stamp

Writes wormlens/_version.py (which is .gitignored). The package's
__init__.py imports __version__ from there at runtime with a static
fallback to the pyproject literal -- so production code does no IO at
import time, and pip-installed copies (no .git) get the stamped value
that was baked in at build.
"""

from __future__ import annotations

import pathlib
import subprocess
import sys
import textwrap

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
VERSION_FILE = REPO_ROOT / "_version.py"


def git_describe():
    if not (REPO_ROOT / ".git").exists():
        return None
    try:
        out = subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "describe", "--tags", "--always", "--dirty"],
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=5,
        ).strip()
        return out or None
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        return None


def write_version(version):
    body = textwrap.dedent(f"""\
        # Auto-generated by tools/stamp_version.py. Do not edit.
        # Regenerated on git pull/checkout via .git/hooks/ and at build time.
        __version__ = "{version}"
        """)
    VERSION_FILE.write_text(body)


def main():
    version = git_describe()
    if version is None:
        print("stamp_version: no git repo found; leaving _version.py untouched", file=sys.stderr)
        return 0
    write_version(version)
    print(f"stamp_version: wrote {VERSION_FILE.relative_to(REPO_ROOT)} ({version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
